# NOTE: Everything test in this file should be in `tools/test-all`.  If there's a
# reason not to run it there, it should be there as a comment
# explaining why.

name: Zulip CI

on:
  push:
    branches: ["*.x", chat.zulip.org, main]
    tags: ["*"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Base images are built using `tools/ci/Dockerfile`.
          # The comments at the top explain how to build and upload these images.
          # Ubuntu 22.04 ships with Python 3.10.12.
          - docker_image: zulip/ci:noble
            name: Ubuntu 24.04 (Python 3.9, backend)
            os: noble
            include_documentation_tests: false
            include_frontend_tests: false
            python_version: "3.9"

          - docker_image: zulip/ci:noble
            name: Ubuntu 24.04 (Python 3.10, backend)
            os: noble
            include_documentation_tests: false
            include_frontend_tests: false
            python_version: "3.10"

          - docker_image: zulip/ci:noble
            name: Ubuntu 24.04 (Python 3.11, backend)
            os: noble
            include_documentation_tests: false
            include_frontend_tests: false
            python_version: "3.11"

          - docker_image: zulip/ci:noble
            name: Ubuntu 24.04 (Python 3.12, backend)
            os: noble
            include_documentation_tests: false
            include_frontend_tests: false
            python_version: "3.12"

    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    container: ${{ matrix.docker_image }}
    env:
      # GitHub Actions sets HOME to /github/home which causes
      # problem later in provision and frontend test that runs
      # tools/setup/postgresql-init-dev-db because of the .pgpass
      # location. PostgreSQL (psql) expects .pgpass to be at
      # /home/github/.pgpass and setting home to `/home/github/`
      # ensures it written there because we write it to ~/.pgpass.
      HOME: /home/github/

    steps:
      - uses: actions/checkout@v6
      #- uses: actions/setup-python@v6
      #  with:
      #    python-version: ${{ matrix.python_version }}
      - name: Install python version
        run: |
          set +e
          yes | sudo apt update
          yes | sudo apt upgrade
          yes | sudo apt install software-properties-common
          yes | sudo add-apt-repository ppa:deadsnakes/ppa
          yes | sudo apt update
          yes | sudo apt-get install python${{ matrix.python_version }}
          shopt -s expand_aliases
          alias python3=python${{ matrix.python_version }}
          python${{ matrix.python_version }} --version
          python3 --version

      - name: Create cache directories
        run: |
          dirs=(/srv/zulip-emoji-cache)
          sudo mkdir -p "${dirs[@]}"
          sudo chown -R github "${dirs[@]}"

      - name: Restore pnpm store
        uses: actions/cache@v4
        with:
          path: /__w/.pnpm-store
          key: v1-pnpm-store-${{ matrix.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ matrix.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: uv-${{ matrix.os }}-

      - name: Restore emoji cache
        uses: actions/cache@v4
        with:
          path: /srv/zulip-emoji-cache
          key: v1-emoji-${{ matrix.os }}-${{ hashFiles('tools/setup/emoji/emoji_map.json', 'tools/setup/emoji/build_emoji', 'tools/setup/emoji/emoji_setup_utils.py', 'tools/setup/emoji/emoji_names.py', 'package.json') }}
          restore-keys: v1-emoji-${{ matrix.os }}

      - name: Install dependencies
        run: |
          alias python=python${{ matrix.python_version }}
          # This is the main setup job for the test suite
          ./tools/ci/setup-backend --skip-dev-db-build
          scripts/lib/clean_unused_caches.py --verbose --threshold=0

      # We run the tests that are only run in a specific job early, so
      # that we get feedback to the developer about likely failures as
      # quickly as possible. Backend/mypy failures that aren't
      # identical across different versions are much more rare than
      # frontend linter or node test failures.
      - name: Run documentation and api tests
        run: |
          source tools/ci/activate-venv
          pip install codecarbon
          ./tools/test-api
      - name: CodeCarbon emissions.csv artifact
        uses: actions/upload-artifact@v4
        with:
          name: codecarbon-emissions
          path: /__w/zulip/zulip/emissions.csv
